#Dockerfile

FROM adoptopenjdk/openjdk16:alpine-jre

WORKDIR /app

COPY build/libs/simplebanking-0.0.1-SNAPSHOT.jar /app/simplebanking-0.0.1-SNAPSHOT.jar

EXPOSE 8080

CMD ["java", "-jar", "simplebanking-0.0.1-SNAPSHOT.jar"]