version: '3.8'

services:
  webapp:
    build: .
    container_name: simple-banking-app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: "docker"
    command: ["java", "-jar", "/app/simplebanking-0.0.1-SNAPSHOT.jar"]